#!/bin/bash

echo && echo --- Cleaning Packages ---
echo
echo --- node ---
make -C ./node clean
rm $GOROOT/pkg/linux_amd64/ghthor/node.a

echo
echo --- buffer ---
make -C ./node/buffer clean
rm $GOROOT/pkg/linux_amd64/ghthor/node/buffer.a

echo
echo --- debug ---
make -C ./debug clean
rm $GOROOT/pkg/linux_amd64/ghthor/debug.a

echo
echo --- object ---
make -C ./object clean
rm $GOROOT/pkg/linux_amd64/ghthor/object.a
