#!/bin/bash

#  This pkg Needs to Be Updated to use the New Server pkg
#make -C ./SortedList clean
#rm $GOROOT/pkg/linux_amd64/ghthor/SortedList.a

#make -C ./Server clean
#rm $GOROOT/pkg/linux_amd64/ghthor/Server.a
make -C ./Init clean
rm $GOROOT/pkg/linux_amd64/ghthor/init.a

make -C ./Debug clean
rm $GOROOT/pkg/linux_amd64/ghthor/debug.a

make -C ./Comm clean
rm $GOROOT/pkg/linux_amd64/ghthor/comm.a

make -C ./Node clean
rm $GOROOT/pkg/linux_amd64/ghthor/node.a

make -C ./Object clean
rm $GOROOT/pkg/linux_amd64/ghthor/object.a

make -C ./Main clean
